var D = [
{n:'Mojito',b:'ron',g:'Vaso alto',m:'machacado',d:2,i:[['Ron blanco',60],['Jugo de limón',30],['Azúcar',2,'cdta'],['Hierbabuena',8,'hojas'],['Soda',90],['Hielo picado',0,'']],
 s:['Pon la hierbabuena y el azúcar en el vaso. Machaca suave 5-6 veces: presiona y gira, sin romper las hojas.','Agrega el jugo de limón y revuelve para disolver el azúcar.','Llena el vaso con hielo picado.','Vierte el ron y revuelve de abajo hacia arriba con la cucharilla.','Completa con soda y corona con más hielo.'],
 t:'Golpea la ramita de decoración contra tu mano antes de ponerla: libera el aroma.',gar:'Ramita de hierbabuena y rodaja de limón'},
{n:'Margarita',b:'tequila',g:'Copa escarchada con sal',m:'batido',d:2,i:[['Tequila',50],['Triple sec',25],['Jugo de limón',25]],
 s:['Escarcha el borde de la copa: pásale limón y gírala sobre un plato con sal.','Pon todos los ingredientes en la coctelera con hielo.','Bate fuerte 12 segundos.','Cuela sobre la copa (con o sin hielo nuevo, a tu gusto).'],
 t:'La proporción mágica es 2-1-1. Memorízala y nunca más necesitarás receta.',gar:'Rodaja de limón'},
{n:'Piña Colada',b:'ron',g:'Vaso alto o copa huracán',m:'batido',d:1,i:[['Ron blanco',50],['Crema de coco',30],['Jugo de piña',90]],
 s:['Pon todo en la licuadora con 1 taza de hielo (o en coctelera si la quieres líquida).','Licúa hasta que quede cremosa y homogénea.','Sirve sin colar.'],
 t:'Si no hay crema de coco: leche de coco + 1 cdta de azúcar.',gar:'Trozo de piña y guinda'},
{n:'Pisco Sour',b:'pisco',g:'Copa baja o flauta',m:'batido',d:2,i:[['Pisco',90],['Jugo de limón',30],['Jarabe simple',22],['Clara de huevo',0,'opcional']],
 s:['Pon todo en la coctelera SIN hielo y bate 10 seg (batido en seco: hace la espuma).','Agrega hielo y bate otros 12 segundos fuertes.','Cuela fino sobre la copa.','Si usaste clara, decora la espuma con 2-3 gotas de amargo.'],
 t:'El batido en seco es el secreto de la espuma sedosa. En Chile suele ir sin clara; en Perú, con.',gar:'Gotas de Angostura sobre la espuma'},
{n:'Daiquiri',b:'ron',g:'Copa cóctel',m:'batido',d:1,i:[['Ron blanco',60],['Jugo de limón',25],['Jarabe simple',15]],
 s:['Todo a la coctelera con bastante hielo.','Bate fuerte 12 segundos, hasta que la coctelera escarche.','Cuela fino a la copa fría.'],
 t:'El favorito de Hemingway. Simple = no hay dónde esconder errores: usa limón recién exprimido.',gar:'Rodaja fina de limón'},
{n:'Caipirinha',b:'ron',g:'Vaso bajo',m:'machacado',d:1,i:[['Cachaça',60],['Limón en cuartos',1,'unidad'],['Azúcar',2,'cdta']],
 s:['Corta el limón en 8 y ponlo en el vaso con el azúcar.','Machaca bien: aquí sí con fuerza, quieres el jugo y los aceites de la cáscara.','Llena de hielo, agrega la cachaça y revuelve.'],
 t:'Si la haces con vodka se llama Caipiroska; con pisco, sorprendentemente rica.',gar:'El mismo limón machacado'},
{n:'Cuba Libre',b:'ron',g:'Vaso alto',m:'directo',d:1,i:[['Ron',50],['Bebida cola',120],['Jugo de limón',10]],
 s:['Llena el vaso de hielo.','Vierte el ron y el jugo de limón.','Completa con cola y revuelve una sola vez, suave.'],
 t:'El chorrito de limón es lo que la separa de un simple "ron con cola".',gar:'Cuña de limón'},
{n:'Gin Tonic',b:'gin',g:'Copa balón',m:'directo',d:1,i:[['Gin',50],['Agua tónica',150]],
 s:['Llena la copa hasta arriba con hielo grande.','Vierte el gin.','Inclina la copa y vierte la tónica por la pared, para conservar el gas.','Revuelve UNA vez.'],
 t:'Enfría la copa antes. Exceso de revolver = tónica muerta.',gar:'Rodaja de limón o pepino, enebro si tienes'},
{n:'Negroni',b:'gin',g:'Vaso bajo',m:'refrescado',d:1,i:[['Gin',30],['Campari',30],['Vermut rojo',30]],
 s:['Pon los tres ingredientes en un vaso con bastante hielo.','Refresca con la cucharilla 20-30 segundos.','Sirve (o cuela sobre un hielo grande nuevo).'],
 t:'Partes iguales: imposible de olvidar. Amargo elegante — si te resulta muy intenso, empieza por el Americano.',gar:'Cáscara de naranja exprimida sobre el trago'},
{n:'Aperol Spritz',b:'vino',g:'Copa balón',m:'directo',d:1,i:[['Prosecco o espumante',90],['Aperol',60],['Soda',30]],
 s:['Llena la copa de hielo.','Vierte en orden: espumante, Aperol, soda.','Revuelve suave una vez.'],
 t:'La regla italiana: 3-2-1. El orden importa: el Aperol después del espumante evita que se vaya al fondo.',gar:'Media rodaja de naranja'},
{n:'Old Fashioned',b:'whisky',g:'Vaso bajo',m:'refrescado',d:2,i:[['Bourbon o whisky',60],['Jarabe simple',10],['Amargo de Angostura',2,'dashes']],
 s:['Pon el jarabe y el amargo en el vaso.','Agrega el whisky y un hielo grande.','Refresca 20 segundos.','Exprime la cáscara de naranja sobre el trago (piel hacia abajo) y pásala por el borde.'],
 t:'El cóctel más antiguo documentado. Menos es más: no le agregues fruta machacada.',gar:'Cáscara de naranja'},
{n:'Manhattan',b:'whisky',g:'Copa cóctel',m:'refrescado',d:2,i:[['Whisky (rye o bourbon)',60],['Vermut rojo',30],['Amargo de Angostura',2,'dashes']],
 s:['Todo a un vaso mezclador con mucho hielo.','Refresca 30 segundos.','Cuela a la copa fría.'],
 t:'El hermano elegante del Old Fashioned. Vermut abierto va SIEMPRE al refrigerador.',gar:'Guinda de cóctel'},
{n:'Whiskey Sour',b:'whisky',g:'Vaso bajo',m:'batido',d:2,i:[['Bourbon',60],['Jugo de limón',25],['Jarabe simple',20],['Clara de huevo',0,'opcional']],
 s:['Batido en seco (sin hielo) 10 seg si usas clara.','Agrega hielo, bate 12 seg más.','Cuela sobre vaso con hielo nuevo.'],
 t:'La familia "sour" (destilado + cítrico + dulce) es la columna vertebral de la coctelería: domina esta fórmula y entenderás 20 tragos de golpe.',gar:'Guinda y media rodaja de naranja'},
];
