D.push(
{n:'Sidecar',b:'licor',g:'Copa cóctel escarchada con azúcar',m:'batido',d:2,i:[['Cognac o brandy',50],['Triple sec',25],['Jugo de limón',25]],
 s:['Escarcha el borde con azúcar.','Todo a la coctelera con hielo, 12 seg.','Cuela fino a la copa.'],
 t:'La Margarita francesa: misma estructura 2-1-1, con cognac. Elegancia de los años 20.',gar:'Cáscara de naranja'},
{n:'French 75',b:'gin',g:'Flauta',m:'batido',d:2,i:[['Gin',30],['Jugo de limón',15],['Jarabe simple',10],['Espumante',90]],
 s:['Gin, limón y jarabe a la coctelera con hielo, 10 seg.','Cuela a la flauta.','Completa con espumante frío, por la pared.'],
 t:'Nombrado por un cañón de la Primera Guerra: burbujas con retroceso.',gar:'Espiral de cáscara de limón'},
{n:'Bramble',b:'gin',g:'Vaso bajo con hielo picado',m:'batido',d:2,i:[['Gin',50],['Jugo de limón',25],['Jarabe simple',15],['Licor de mora (crème de mûre)',15]],
 s:['Gin, limón y jarabe a la coctelera, batir 10 seg.','Cuela sobre vaso lleno de hielo picado.','Vierte el licor de mora encima: se filtrará en vetas moradas.'],
 t:'Clásico moderno de Londres (1984). Sin licor de mora, sirve mermelada de mora batida dentro.',gar:'Moras frescas y limón'},
{n:'Gimlet',b:'gin',g:'Copa cóctel',m:'batido',d:1,i:[['Gin',60],['Jugo de limón',20],['Jarabe simple',20]],
 s:['Todo a la coctelera con hielo.','Bate 12 segundos.','Cuela fino a la copa fría.'],
 t:'El sour de gin en su forma más pura. Con vodka se llama Vodka Gimlet.',gar:'Rodaja fina de limón'},
{n:'Clover Club',b:'gin',g:'Copa cóctel',m:'batido',d:3,i:[['Gin',45],['Jugo de limón',15],['Jarabe de frambuesa',15],['Clara de huevo',0,'']],
 s:['Batido en seco 10 segundos (aquí la clara no es opcional).','Con hielo, bate fuerte 15 seg.','Cuela fino: espuma rosada perfecta.'],
 t:'Jarabe de frambuesa casero: partes iguales frambuesas y azúcar, reposar, colar.',gar:'3 frambuesas en escarbadientes'},
{n:'Penicillin',b:'whisky',g:'Vaso bajo',m:'batido',d:3,i:[['Whisky escocés',50],['Jugo de limón',22],['Jarabe de miel y jengibre',22],['Whisky ahumado (Islay)',7]],
 s:['Jarabe: miel + agua + láminas de jengibre, calentar y colar.','Whisky, limón y jarabe a la coctelera, 12 seg.','Cuela sobre hielo grande.','Flota el whisky ahumado encima.'],
 t:'Clásico moderno (2005). El primer aroma es humo, el trago es miel y jengibre: teatro puro.',gar:'Jengibre confitado'},
{n:'Zombie',b:'ron',g:'Vaso alto grande',m:'batido',d:3,i:[['Ron blanco',30],['Ron añejo',30],['Ron oscuro',30],['Jugo de limón',20],['Jugo de piña',30],['Granadina',10],['Angostura',1,'dash']],
 s:['Todo a la coctelera con hielo, bate 10 seg.','Cuela sobre vaso grande lleno de hielo picado.','Decora tiki: cuanto más exagerado, mejor.'],
 t:'Su creador limitaba a 2 por cliente. Tres rones distintos: respeta el límite.',gar:'Piña, guinda, hierbabuena — todo'},
{n:'Hurricane',b:'ron',g:'Copa huracán o vaso alto',m:'batido',d:2,i:[['Ron blanco',30],['Ron oscuro',30],['Jugo de maracuyá',30],['Jugo de naranja',30],['Jugo de limón',15],['Granadina',15]],
 s:['Todo a la coctelera con hielo.','Bate 10 segundos.','Cuela sobre vaso con hielo abundante.'],
 t:'El trago de Nueva Orleans para Mardi Gras. El maracuyá manda: que sea jugo real.',gar:'Rodaja de naranja y guinda'},
{n:'Blue Lagoon',b:'vodka',g:'Vaso alto',m:'directo',d:1,i:[['Vodka',40],['Curaçao azul',20],['Limonada o soda + limón',120]],
 s:['Vaso con hielo: vodka y curaçao.','Completa con limonada y revuelve.'],
 t:'El curaçao azul es triple sec teñido: sabor naranja, color piscina.',gar:'Rodaja de limón y guinda'},
{n:'Terremoto',b:'vino',g:'Vaso grande',m:'directo',d:1,i:[['Vino pipeño (o blanco dulce)',200],['Helado de piña',2,'bolas'],['Granadina',15],['Fernet (opcional)',10]],
 s:['Vaso grande: el vino primero.','Las bolas de helado de piña encima.','Granadina y, si quieres, el toque de fernet.','Se toma revolviendo el helado a medida que se derrite.'],
 t:'El clásico chileno de fondas. El segundo se llama "réplica", y suele ser mala idea.',gar:'Bombilla y cuchara'},
{n:'Piscola',b:'pisco',g:'Vaso alto',m:'directo',d:1,i:[['Pisco',60],['Bebida cola',120]],
 s:['Vaso con bastante hielo.','Pisco primero, cola después.','Revuelve una vez. Listo: es la piscola, no la compliquemos.'],
 t:'El trago nacional por goleada. Proporción clásica "medio a medio" para valientes; 1 a 2 es más civilizado.',gar:'Rodaja de limón opcional'},
{n:'Aperol Sour',b:'licor',g:'Vaso bajo',m:'batido',d:2,i:[['Aperol',60],['Jugo de limón',25],['Jarabe simple',10],['Clara de huevo',0,'opcional']],
 s:['Batido en seco si usas clara.','Con hielo, 12 segundos.','Cuela sobre hielo nuevo.'],
 t:'Para quienes aman el Spritz: el mismo amargor naranja en formato sour.',gar:'Media rodaja de naranja'},
{n:'Mula Chilena',b:'pisco',g:'Vaso alto o tazón',m:'directo',d:1,i:[['Pisco',50],['Jugo de limón',15],['Ginger beer',120]],
 s:['Vaso lleno de hielo.','Pisco y limón.','Completa con ginger beer, revuelve suave.'],
 t:'El Moscow Mule criollo: el pisco le da un carácter más frutal que el vodka.',gar:'Cuña de limón y hierbabuena'}
);
