D.push(
{n:'Gin Fizz',b:'gin',g:'Vaso alto sin hielo',m:'batido',d:2,i:[['Gin',45],['Jugo de limón',25],['Jarabe simple',15],['Clara de huevo',0,'opcional'],['Soda',60]],
 s:['Batido en seco si usas clara (10 seg sin hielo).','Agrega hielo, bate fuerte 15 seg.','Cuela al vaso SIN hielo y completa con soda: la espuma crecerá.'],
 t:'La diferencia con el Collins: batido más largo, sin hielo en el vaso, más espuma.',gar:'Cáscara de limón'},
{n:'Dark \'n\' Stormy',b:'ron',g:'Vaso alto',m:'directo',d:1,i:[['Ron oscuro',60],['Ginger beer',120],['Jugo de limón',10]],
 s:['Vaso con hielo, ginger beer primero.','Flota el ron oscuro encima: queda la "tormenta" en dos capas.','Cuña de limón exprimida encima.'],
 t:'El trago nacional de Bermudas. Verterlo al revés (ron al final) es lo que crea el efecto visual.',gar:'Cuña de limón'},
{n:'Mint Julep',b:'whisky',g:'Vaso bajo o tazón metálico',m:'machacado',d:2,i:[['Bourbon',60],['Jarabe simple',10],['Hierbabuena',8,'hojas'],['Hielo picado',0,'']],
 s:['Machaca suave la hierbabuena con el jarabe en el vaso.','Llena con hielo picado hasta el tope.','Agrega el bourbon y revuelve hasta que el vaso escarche por fuera.','Corona con más hielo picado en montañita.'],
 t:'El trago del Derby de Kentucky. Es un mojito sureño: bourbon en vez de ron, sin soda.',gar:'Ramo generoso de hierbabuena'},
{n:'Sazerac',b:'whisky',g:'Vaso bajo sin hielo',m:'refrescado',d:3,i:[['Whisky rye o cognac',60],['Jarabe simple',10],['Amargo Peychaud o Angostura',3,'dashes'],['Absenta (enjuague)',5]],
 s:['Enjuaga el vaso con la absenta: gírala cubriendo las paredes y desecha el exceso.','En otro vaso con hielo, refresca whisky, jarabe y amargo 25 seg.','Cuela al vaso perfumado, sin hielo.','Cáscara de limón exprimida encima (y se descarta).'],
 t:'El cóctel oficial de Nueva Orleans. El enjuague de absenta perfuma sin dominar.',gar:'Ninguna dentro — solo el aroma'},
{n:'Boulevardier',b:'whisky',g:'Vaso bajo',m:'refrescado',d:1,i:[['Bourbon',30],['Campari',30],['Vermut rojo',30]],
 s:['Los tres al vaso con bastante hielo.','Refresca 25 segundos.'],
 t:'Un Negroni donde el gin cede su lugar al bourbon: más cálido, ideal de invierno.',gar:'Cáscara de naranja'},
{n:'Americano',b:'licor',g:'Vaso alto',m:'directo',d:1,i:[['Campari',30],['Vermut rojo',30],['Soda',60]],
 s:['Vaso con hielo: Campari y vermut.','Completa con soda, revuelve una vez.'],
 t:'El abuelo del Negroni y perfecto para iniciarse en lo amargo: la soda lo suaviza.',gar:'Media rodaja de naranja'},
{n:'Bellini',b:'vino',g:'Flauta',m:'directo',d:1,i:[['Puré de durazno',50],['Prosecco frío',100]],
 s:['Puré de durazno bien frío en la flauta.','Vierte el prosecco lentamente, inclinando la copa.','Revuelve suave con la cucharilla.'],
 t:'Nació en el Harry\'s Bar de Venecia. Durazno natural licuado, no néctar de caja.',gar:'Nada'},
{n:'Mimosa',b:'vino',g:'Flauta',m:'directo',d:1,i:[['Jugo de naranja frío',75],['Espumante frío',75]],
 s:['Jugo primero, espumante después, por la pared.','No revolver: las burbujas mezclan solas.'],
 t:'Mitad y mitad, todo muy frío, jugo recién exprimido. El brunch en una copa.',gar:'Nada'},
{n:'Sangría',b:'vino',g:'Jarra + copas',m:'directo',d:1,i:[['Vino tinto',750],['Jugo de naranja',200],['Brandy',60],['Azúcar',3,'cda'],['Fruta picada (naranja, manzana)',2,'tazas']],
 s:['En la jarra: fruta, azúcar y brandy. Deja macerar 15 min.','Agrega el vino y el jugo, revuelve.','Refrigera mínimo 2 horas (mejor 4).','Sirve en copas con hielo.'],
 t:'Rinde ~6 copas. Mejora con las horas: hazla en la mañana para la noche.',gar:'La misma fruta macerada'},
{n:'Michelada',b:'licor',g:'Vaso alto escarchado',m:'directo',d:1,i:[['Cerveza clara',330],['Jugo de limón',30],['Salsa inglesa',3,'dashes'],['Tabasco',2,'dashes'],['Sal y merquén o chile en polvo',0,'']],
 s:['Escarcha el vaso con sal y merquén.','Jugo de limón y salsas al fondo, con hielo.','Vierte la cerveza inclinando el vaso.'],
 t:'Versión mínima ("chelada"): solo limón y sal. Desde ahí, construye tu picante ideal.',gar:'Cuña de limón'},
{n:'Rusty Nail',b:'whisky',g:'Vaso bajo',m:'directo',d:1,i:[['Whisky escocés',45],['Drambuie',25]],
 s:['Vaso con hielo grande.','Ambos ingredientes, refresca 15 segundos.'],
 t:'Drambuie es licor de whisky con miel y hierbas: el trago es whisky endulzándose a sí mismo.',gar:'Cáscara de limón'},
{n:'Godfather',b:'whisky',g:'Vaso bajo',m:'directo',d:1,i:[['Whisky escocés',45],['Amaretto',25]],
 s:['Vaso con hielo grande.','Ambos ingredientes, refrescar breve.'],
 t:'El amaretto (licor de almendra) redondea el whisky. Dicen que era el trago de Marlon Brando.',gar:'Nada'},
{n:'Amaretto Sour',b:'licor',g:'Vaso bajo',m:'batido',d:2,i:[['Amaretto',60],['Jugo de limón',25],['Jarabe simple',10],['Clara de huevo',0,'opcional']],
 s:['Batido en seco si usas clara.','Con hielo, 12 segundos fuertes.','Cuela sobre hielo nuevo.'],
 t:'El sour más amable para quien no toma fuerte: dulce de almendra + ácido.',gar:'Guinda y rodaja de naranja'}
);
