D.push(
{n:'Martini seco',b:'gin',g:'Copa cóctel',m:'refrescado',d:2,i:[['Gin',75],['Vermut seco',15]],
 s:['Vaso mezclador lleno de hielo, ambos ingredientes.','Refresca 30 segundos — paciencia, la dilución es parte de la receta.','Cuela a la copa bien fría.'],
 t:'"Batido, no revuelto" es de película: revuelto queda más sedoso. Más vermut = más amable para empezar.',gar:'Aceituna o cáscara de limón (elige bando)'},
{n:'Cosmopolitan',b:'vodka',g:'Copa cóctel',m:'batido',d:2,i:[['Vodka citron',40],['Triple sec',15],['Jugo de arándano',30],['Jugo de limón',15]],
 s:['Todo a la coctelera con hielo.','Bate 12 segundos.','Cuela fino a la copa fría.'],
 t:'Debe quedar rosado translúcido, no rojo opaco: si quedó oscuro, te pasaste de arándano.',gar:'Cáscara de limón flameada si te atreves'},
{n:'Moscow Mule',b:'vodka',g:'Tazón de cobre o vaso alto',m:'directo',d:1,i:[['Vodka',50],['Jugo de limón',15],['Ginger beer',120]],
 s:['Llena el vaso de hielo.','Vodka y limón primero.','Completa con ginger beer y revuelve suave.'],
 t:'Ginger beer ≠ ginger ale: la beer es más picante y es la correcta. El cobre es tradición, no requisito.',gar:'Cuña de limón y hoja de menta'},
{n:'Bloody Mary',b:'vodka',g:'Vaso alto',m:'directo',d:2,i:[['Vodka',50],['Jugo de tomate',120],['Jugo de limón',15],['Salsa inglesa',3,'dashes'],['Tabasco',2,'dashes'],['Sal y pimienta',0,'']],
 s:['En el vaso con hielo, vierte todo.','Método "rolling": pasa el contenido de un vaso a otro 3-4 veces para mezclar sin airear.','Ajusta picante y sal a tu gusto.'],
 t:'El único cóctel que se acepta desayunar. El apio es decoración funcional: revuelve con él.',gar:'Rama de apio, limón'},
{n:'Tequila Sunrise',b:'tequila',g:'Vaso alto',m:'directo',d:1,i:[['Tequila',50],['Jugo de naranja',120],['Granadina',15]],
 s:['Vaso con hielo: tequila y jugo de naranja, revuelve.','Vierte la granadina lentamente por el borde: se hundirá formando el "amanecer".','No revuelvas más — el degradé es el punto.'],
 t:'La granadina cae porque tiene más azúcar (más densidad). Física aplicada al bar.',gar:'Rodaja de naranja y guinda'},
{n:'Sex on the Beach',b:'vodka',g:'Vaso alto',m:'directo',d:1,i:[['Vodka',40],['Licor de durazno',20],['Jugo de naranja',60],['Jugo de arándano',60]],
 s:['Vaso alto lleno de hielo.','Vodka y licor de durazno primero.','Completa con ambos jugos y revuelve.'],
 t:'Dulce y traicionero: se toma como jugo. Avisado estás.',gar:'Rodaja de naranja'},
{n:'Long Island Iced Tea',b:'vodka',g:'Vaso alto',m:'directo',d:2,i:[['Vodka',15],['Gin',15],['Ron blanco',15],['Tequila',15],['Triple sec',15],['Jugo de limón',25],['Jarabe simple',20],['Bebida cola',30]],
 s:['Todo menos la cola a la coctelera con hielo, bate 10 seg.','Cuela sobre vaso alto con hielo.','Corona con la cola: solo para dar color de "té".'],
 t:'Cinco destilados y no sabe a alcohol: el trago más engañoso del recetario. Uno por noche.',gar:'Cuña de limón'},
{n:'Mai Tai',b:'ron',g:'Vaso bajo',m:'batido',d:3,i:[['Ron añejo',40],['Ron oscuro',20],['Curaçao naranja',15],['Jugo de limón',25],['Jarabe de almendra (orgeat)',10]],
 s:['Todo menos el ron oscuro a la coctelera con hielo picado.','Bate corto (5 seg) y vierte sin colar al vaso.','Flota el ron oscuro encima vertiendo sobre el dorso de la cucharilla.'],
 t:'El rey tiki. El orgeat se consigue en tiendas de repostería o se hace con almendras + azúcar + agua.',gar:'Hierbabuena y cáscara de limón'},
{n:'Espresso Martini',b:'vodka',g:'Copa cóctel',m:'batido',d:2,i:[['Vodka',40],['Licor de café',20],['Espresso frío',30],['Jarabe simple',10]],
 s:['Prepara el espresso y déjalo enfriar un par de minutos.','Todo a la coctelera con mucho hielo.','Bate MUY fuerte 15 seg: la crema del café hace la espuma.','Cuela fino a la copa: debe quedar una capa de espuma dorada.'],
 t:'Café recién hecho, nunca de ayer: la crema fresca es la que espuma.',gar:'3 granos de café sobre la espuma'},
{n:'White Russian',b:'vodka',g:'Vaso bajo',m:'directo',d:1,i:[['Vodka',50],['Licor de café',20],['Crema de leche',30]],
 s:['Vaso con hielo: vodka y licor de café, revuelve.','Flota la crema encima vertiendo sobre la cucharilla.','Se revuelve al tomar (o antes, a gusto).'],
 t:'El trago de El Gran Lebowski. Con leche en vez de crema queda más liviano.',gar:'Nada — el degradé es la gracia'},
{n:'Black Russian',b:'vodka',g:'Vaso bajo',m:'directo',d:1,i:[['Vodka',50],['Licor de café',25]],
 s:['Vaso con hielo.','Ambos ingredientes, refrescar 10 segundos.'],
 t:'White Russian sin crema. Dos ingredientes: imposible fallar.',gar:'Nada'},
{n:'Paloma',b:'tequila',g:'Vaso alto escarchado con sal',m:'directo',d:1,i:[['Tequila',50],['Jugo de pomelo',60],['Jugo de limón',15],['Soda de pomelo',60],['Pizca de sal',0,'']],
 s:['Escarcha el borde con sal (opcional pero recomendado).','Vaso con hielo: tequila, jugos y la pizca de sal.','Completa con la soda y revuelve suave.'],
 t:'En México se toma más Paloma que Margarita. La pizca de sal DENTRO despierta el pomelo.',gar:'Rodaja de pomelo'},
{n:'Tom Collins',b:'gin',g:'Vaso alto',m:'batido',d:1,i:[['Gin',45],['Jugo de limón',25],['Jarabe simple',15],['Soda',90]],
 s:['Gin, limón y jarabe a la coctelera con hielo, bate 10 seg.','Cuela sobre vaso alto con hielo.','Completa con soda.'],
 t:'Una "limonada de adultos". Fórmula sour + soda = familia Collins.',gar:'Rodaja de limón y guinda'}
);
